links = ['https://drive.google.com/file/d/1AwQEddLHwidkZpNs5mlVCstR5dqhBEIa/view?usp=sharing',
'https://drive.google.com/file/d/1vx3P6LswH6s4IKTi1HhAr4Op81HDZj15/view?usp=sharing',
'https://drive.google.com/file/d/1p_u_sIrDQGNssVQU55Fn_rvTbqnpi2qd/view?usp=sharing',
'https://drive.google.com/file/d/1cCMesTyvV5U3WhHpSGojSpOepNJi0m8y/view?usp=sharing',
'https://drive.google.com/file/d/1NPdzCIYk76HKCT8qQe4Ly07j_3bPBHuj/view?usp=sharing',
'https://drive.google.com/file/d/11v_0KTRFAw0kVs2x2Jyyd3BdS4p-Enb2/view?usp=sharing',
'https://drive.google.com/file/d/1YOTtWkc53rrOKQc7cJiuuSXl7OBl9SWa/view?usp=sharing',
'https://drive.google.com/file/d/1mp6SEt5N3KtODzQQ_ifQaeVMDx6bl3jf/view?usp=sharing',
'https://drive.google.com/file/d/1x2u6pN0JzhTGVaaAAZSsZ1vRIWgDRITr/view?usp=sharing',
'https://drive.google.com/file/d/10eYo7ZMsOtspZPXrfHemR3j2Hs8FCX1W/view?usp=sharing',
'https://drive.google.com/file/d/1bMAOuKmziS7Is4BXf4VGMWlP44OPB70g/view?usp=sharing',
'https://drive.google.com/file/d/1blPzQ5hYIxVgv3QdHCQsS8iHwh0S4Bzr/view?usp=sharing',
'https://drive.google.com/file/d/1ftbfvVvBZifrFLTlEhWD26pnT_AM5aY4/view?usp=sharing',
'https://drive.google.com/file/d/119Qy5iRCX43O0wqbRYvfBh96_grf0fCc/view?usp=sharing',
'https://drive.google.com/file/d/1Gw-B4qmukqwFDh5m01QHbczEmJ0oA-Ny/view?usp=sharing',
'https://drive.google.com/file/d/1dzCM_M0oHc0ORcFtfYg5tFJKhNIu1NjL/view?usp=sharing',
'https://drive.google.com/file/d/1siyjwNE49AIljLslDcP1emNqPVeBCJY9/view?usp=sharing']
